---
- hosts: all
  gather_facts: true

- hosts: master-lbs
  vars: 
    ports:
    - "{{ lb_master_port }}/tcp"
    lb_type: master
    haproxy_template: master-haproxy.conf.j2
    lb_vip: "{{ lb_master_vip }}" 
  roles:
  - role: manage-loadbalancers
  
- hosts: infranode-lbs
  vars: 
    ports:
    - 80/tcp
    - 443/tcp
    lb_type: infranode
    haproxy_template: infranode-haproxy.conf.j2
    lb_vip: "{{ lb_infranode_vip }}" 
  roles:
  - role: manage-loadbalancers