#- load ip_vs iptables and ipset modules

- name: install python-firewall
  package:
    name: python-firewall
    state: present
  when: os_firewall_use_firewalld        

- name: open VRRP port - firewalld
  firewalld:
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: true
    state: enabled
    immediate: true
  when: os_firewall_use_firewalld   
  
- name: open VRRP port - iptables
  iptables: 
    chain: INPUT
    protocol: vrrp
    jump: ACCEPT
  when: not os_firewall_use_firewalld
  
- name: reload iptables
  service:
    name: iptables
    state: restarted
  when: not os_firewall_use_firewalld  
  
- name: 'Enable IP forwading'
  lineinfile: 
    path: /etc/sysctl.d/50-keepalived.conf
    regexp: '^net.ipv4.ip_forward.*'
    line: 'net.ipv4.ip_forward=1'
    create: yes
    state: present
    owner: root
    group: root
    mode: 0644

- name: 'reload sysctl'
  command: sysctl -p  
           

- name: make sure conf dir is present
  file:
    name: "{{ static_pod_config_path }}"
    state: directory 
    
- name: create masters keepalived configuration
  template:
    src: masters-keepalived.conf.j2
    dest: "{{ static_pod_config_path }}/masters-keepalived.conf"

- name: make sure pod dir is present
  file:
    name: "{{ static_pod_manifest_path }}"
    state: directory

- name: create masters keepalived pod definition
  template:
    src: masters-keepalived-pod.yaml.j2
    dest: "{{ static_pod_manifest_path }}/masters-keepalived-pod.yaml"